# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jimmy Chen
url:              //jimmychen.org
paginate:         5
baseurl:          /
header:           "http:"
author:
  name:           Jimmy Chen
  url:            
  email:          jimmy@jimmy.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed
