# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jimmy Chen
url:              //jimmychen.org
paginate:         5
baseurl:
header:           "http:"
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen_org
  email:          jimmy@jimmychen.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed

variables:
  primary-color: "#bf1f49"
