# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jimmy Chenfdfs
url:              //jimmychen.org
paginate:         5
baseurl:          /
header:           "http:"
author:
  name:           Jimmy Chen
  url:
user.email:          jimmy@jimmychen.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed
